config/routes.rb
Rails.application.routes.draw do

  get 'comments/edit'

  get 'comments/update'

  get 'comments/new'

  get 'debates/index'

  get 'debates/show'

  get 'users/show'

  get 'static_pages/live_debate'

  devise_for :users

  resources :users, :debates, :comments

  root 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :debate
end

app/models/debate.rb
class Debate < ActiveRecord::Base
  has_many :debatements
  has_many :users, through: :debatements

  has_many :comments
end

app/models/debatement.rb
class Debatement < ActiveRecord::Base
  belongs_to :user
  belongs_to :debate
end

app/models/debates_users.rb
class DebatesUsers < ActiveRecord::Base
  belongs_to :debate
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :debatements
  has_many :debates, through: :debatements


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
  end

  def update
  end

  def new

  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:success] = "Thanks for contributing!"
    else
      flash[:danger] = comment.errors.messages
    end
    redirect_to :back # Go back to page regardless
  end

  private

  def comment_params
    params.require(:comment).permit(:authored_by, :description, :debate_id, :side)
  end
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  def index
    @debates = Debate.all
  end

  def show
    @debate = Debate.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @debates = Debate.all
    @current_debate = Debate.first
  end

  def live_debate
    @random_user = User.all.sample
    @random_debate = Debate.all.sample
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :show, :update]


  def show
  end

  def edit
  end


  def update
    @user.update_attributes(user_params)
    render 'show'
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/debates/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Past Debates</h1>
  </div>

  <div class="col-lg-4 col-md-4">

  <ul class="list-group">
     <% @debates.each do |debate|%>
    <li class="list-group-item">
      <span class="badge"><%= debate.users.count %></span>
        <%= link_to "#{debate.title} ", debate %>
      </li>
   <% end %>
</ul>
    </div>
</div>

app/views/debates/show.html.erb
<div class="container">
  <!-- Main component for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1><%= @debate.title %></h1>
    <!--<p><%= @debate.description %></p>-->
    <h3>Winner: <%= @debate.winner %></h3>
  </div>
</div>
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-6">
      <h1>Apple </h1>
      <h1>Submit a comment</h1>
      <%= form_for(Comment.new, class: 'form-group') do |f| %>
        <%= f.text_field :authored_by, class:"form-control input-lg form-group", placeholder: "Name"  %>
        <%= f.text_area  :description, class:"form-control input-lg form-group", placeholder: "Description"  %>
        <%= f.hidden_field :debate_id, value: @debate.id %>
        <%= f.hidden_field :side, value: 1 %>
        <div class="form-group">
          <%= f.submit "Submit link", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
      <% @debate.comments.where(side: 1).each do |comment| %>
        <h2><%= comment.authored_by %></h2>
        <p> <%= comment.description %> </p>
      <% end %>
    </div>
    <div class="col-md-6">
      <h1>Android</h1>
      <h1>Submit a comment</h1>
      <%= form_for(Comment.new, class: 'form-group') do |f| %>
        <%= f.text_field :authored_by, class:"form-control input-lg form-group", placeholder: "Name"  %>
        <%= f.text_area  :description, class:"form-control input-lg form-group", placeholder: "Description"  %>
        <%= f.hidden_field :debate_id, value: @debate.id %>
        <%= f.hidden_field :side, value: 2 %>
        <div class="form-group">
          <%= f.submit "Submit link", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
      <% @debate.comments.where(side: 2).each do |comment| %>
        <h2><%= comment.authored_by %></h2>
        <p> <%= comment.description %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse " role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand " href="<%= root_path %>">Tech-<strong>Debate</strong></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
          <li><%= link_to "Live Debate!", static_pages_live_debate_path %> </li>
          <li><%= link_to "Job Offers", nil %> </li>
          <li> <a href="<%= debates_path %>">Past debates</a> </li>
          <li><%= link_to "Profile", current_user %> </li>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
          <li> <a>Signed in as <%= current_user.email %></a> </li>
       <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %> </li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
       <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechDebate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>
</html>

app/views/static_pages/home.html.erb
<div id="colordiv">

  <div id="whatwedo" class="row">
    <h1 class="text-center customheader">Debate Of The Month</h1>

    <div class="col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h4 class="text-center">Debate Topic of the Month</h4>
        </div>
        <div style="margin: 61px;">
          <h3 class="text-center">Apple</h3>
          <img src='http://t2.gstatic.com/images?q=tbn:ANd9GcT8HOctyI-laD1q6s9bQvTvfippQYd_9CDfdeUCa4xcq9pgrduJ' style="width:100px">
          <h2 class="text-center">VS</h2>
          <h2 class="text-center">Android</h2>
          <img src='http://nerdynerdnerdz.com/wp-content/uploads/2014/07/Android-att-apn-mms.jpg'
               style="width:180px">
        </div>
        <div class="panel-footer text-center">
          <span class="fa fa-crosshairs bigicon"></span>
        </div>
      </div>
    </div>
    <div class="section" style="color:white">
      <div class="col-md-8 col-lg-8">
        <div class="transbox">
          <div class="panel-heading">
            <h3 class="text-center">About Apple</h3>
          </div>
          <div style="margin: 30px;">
            Apple Inc. is an American multinational corporation headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, online services, and personal computers. Its best-known hardware products are the Mac line of computers, the iPod media player, the iPhone smartphone, and the iPad tablet computer. Its online services include iCloud, iTunes Store, and App Store. Apple's consumer software includes the OS X and iOS operating systems, the iTunes media browser, the Safari web browser, and the iLife and iWork creativity and productivity suites.
            <br>
            <br>
            Apple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne on April 1, 1976, to develop and sell personal computers. It was incorporated as Apple Computer, Inc. on January 3, 1977, and was renamed as Apple Inc. on January 9, 2007, to reflect its shifted focus towards consumer electronics.
            <br>
            <br>
            Apple is the world's second-largest information technology company by revenue after Samsung Electronics, and the world's third-largest mobile phone maker after Samsung and Nokia. Fortune magazine named Apple the most admired company in the United States in 2008, and in the world from 2008 to 2012. On September 30, 2013, Apple surpassed Coca-Cola to become the world's most valuable brand in the Omnicom Group's "Best Global Brands" report. However, the company has received criticism for its contractors' labor practices, as well as for its own environmental and business practices.
          </div>
        </div>
         <div class="transbox">
            <div class="panel-heading">
              <h4 class="text-center">About Android</h4>
            </div>
            <div style="margin: 30px;">
              Android is a mobile operating system (OS) based on the Linux kernel and currently developed by Google. With a user interface based on direct manipulation, Android is designed primarily for touchscreen mobile devices such as smartphones and tablet computers, with specialized user interfaces for televisions (Android TV), cars (Android Auto), and wrist watches (Android Wear). The OS uses touch inputs that loosely correspond to real-world actions, like swiping, tapping, pinching, and reverse pinching to manipulate on-screen objects, and a virtual keyboard. Despite being primarily designed for touchscreen input, it also has been used in game consoles, digital cameras, and other electronics.
              <br>
              <br>
              Android is the most popular mobile OS. As of 2013, Android devices sell more than Windows, iOS, and Mac OS devices combined, with sales in 2012, 2013 and 2014 close to the installed base of all PCs. As of July 2013 the Google Play store has had over 1 million Android apps published, and over 50 billion apps downloaded.[20] A developer survey conducted in April–May 2013 found that 71% of mobile developers develop for Android.At Google I/O 2014, the company revealed that there were over 1 billion active monthly Android users (that have been active for 30 days), up from 538 million in June 2013.
              <br>
              <br>
              Android's source code is released by Google under open source licenses, although most Android devices ultimately ship with a combination of open source and proprietary software. Initially developed by Android, Inc., which Google backed financially and later bought in 2005, Android was unveiled in 2007 along with the founding of the Open Handset Alliance—​a consortium of hardware, software, and telecommunication companies devoted to advancing open standards for mobile devices.
            </div>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/live_debate.html.erb
<div class="container">

  <div class="jumbotron">
    <p>You have been paired with: </p><h1><%= @random_user.name %></h1>
    <p>About</p>
    <h2><%= @random_debate.title %></h2>
  </div>



<div class="row">
    <div class="col-md-12">
      <h1>Submit an opening argument</h1>
      <%= form_for(Comment.new, class: 'form-group') do |f| %>
        <%= f.text_field :authored_by, class:"form-control input-lg form-group", placeholder: "Name"  %>
        <%= f.text_area  :description, class:"form-control input-lg form-group", placeholder: "Description"  %>
        <%= f.hidden_field :debate_id, value: 1 %>
        <%= f.hidden_field :side, value: 1 %>
        <div class="form-group">
          <%= f.submit "Submit link", class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  Last name : <%= f.text_field :name %><br />
  About : <%= f.text_area :about %><br />
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="col-lg-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-magnet"></i> Control Panel</h3>
      </div>
      <div class="panel-body">
        <%= link_to "Change your password", edit_user_registration_path, class: 'btn btn-md  btn-primary' %>
        <%= link_to "Change your information", edit_user_path(@user), class: 'btn btn-md btn-primary'%>
      </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-magnet"></i> Profile</h3>
      </div>
      <div class="panel-body">
        <%= gravatar_for(@user) %>
        <h1>Name:</h1>
        <%= @user.name %>
        <h1>About:</h1>
        <%= @user.about %>
        <h1>Debates Participated in:</h1>
        <ul>
        <% @user.debates.each do |debate| %>
         <li><%= debate.title %></li>
        <% end %>
        </ul>
        <h1>Social:</h1>
        <%= social_share_button_tag("My Site") %>
      </div>
    </div>
  </div>
</div>



<style>
  .btn-hover {
    font-weight: normal;
    color: #333333;
    cursor: pointer;
    background-color: inherit;
    border-color: transparent;
  }

  .btn-hover-alt {
    font-weight: normal;
    color: #ffffff;
    cursor: pointer;
    background-color: inherit;
    border-color: transparent;
  }
</style>